Use `keyword_do`
This change makes `lrama` command to raise an error

```
$ bundle exec exe/lrama sample/ruby_3_2/parse.tmp.y

bundler: failed to load command: exe/lrama (exe/lrama)
/Users/kaneko.y/source/yui-knk/lrama/lib/lrama/state.rb:436:in `block in goto_follow_set': undefined method `[]' for nil (NoMethodError)

        .select {|kernel| @lalr_isocore.follow_kernel_items[goto][kernel] }
                                                                 ^^^^^^^^
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/state.rb:436:in `select'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/state.rb:436:in `goto_follow_set'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/state.rb:264:in `block in propagate_lookaheads'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/state.rb:258:in `map'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/state.rb:258:in `propagate_lookaheads'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/states.rb:738:in `compute_state'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/states.rb:702:in `block (2 levels) in split_states'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/states.rb:701:in `each'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/states.rb:701:in `block in split_states'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/states.rb:700:in `each'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/states.rb:700:in `split_states'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/states.rb:142:in `block in compute_ielr'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/tracer/duration.rb:26:in `report_duration'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/states.rb:142:in `compute_ielr'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/command.rb:85:in `compute_status'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/command.rb:32:in `execute_command_workflow'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/command.rb:21:in `block (2 levels) in run'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/reporter/profile/memory.rb:20:in `report'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/command.rb:20:in `block in run'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/reporter/profile/call_stack.rb:27:in `report'
	from /Users/kaneko.y/source/yui-knk/lrama/lib/lrama/command.rb:19:in `run'
	from exe/lrama:7:in `<top (required)>'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/bin/bundle:25:in `load'
	from /Users/kaneko.y/.rbenv/versions/3.3.0/bin/bundle:25:in `<main>'
```